<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$title = 'Déconnexion';
 $this->headTitle($title);
 ?>
<hr><a href="Z:\public_html\zend_tuto\module\SanAuth\view\san-auth\auth\login.phtml"<?php echo $this->escapeHtml($title); ?><hr>
 
 
           
        
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'disconnect')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
