<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 $title = 'Mes albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">emprunter un nouveau album </a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Auteur</th>
     <th>A rendre le</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td><?php echo "pas de date" ?></td>
     <td>
         
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id_album));?>">rendre</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
